import os
import sys
import json
from pathlib import Path

# Add src to sys.path
sys.path.insert(0, str(Path("src").resolve()))
import config
from step1_extractor import run_step1
from step2_llm import run_step2
from step3_tts import run_step3
from step4_rvc import run_step4
from step5_video import run_step5

print("=======================================================")
print("🚀 BẮT ĐẦU CHẠY PIPELINE BÀI GIẢNG DIỄN THUYẾT TRUYỀN CẢM")
print("=======================================================")

# Load script generated by Gemini
with open("workspace/script.json", "r", encoding="utf-8") as f:
    scripts = json.load(f)

# 3. Dọn dẹp cache audio cũ
for f in config.BASE_AUDIO_DIR.glob("*.mp3"):
    try: f.unlink()
    except Exception: pass
for f in config.FINAL_AUDIO_DIR.glob("*.mp3"):
    try: f.unlink()
    except Exception: pass

# 4. Sinh giọng đọc Microsoft Nam Minh (-4% speed, nhấn nhá)
print("\n[*] Đang sinh giọng đọc lồng tiếng truyền cảm (-4% speed)...")
audio_records = run_step3(scripts, voice_name="vi-VN-NamMinhNeural")

# 5. Hoàn thiện audio records
final_records = run_step4(audio_records=audio_records, enable_rvc=False)

# 6. Lắp ráp video hoàn chỉnh
print("\n[*] Đang lắp ráp video bài giảng hoàn chỉnh...")
out_video = run_step5(slide_items=final_records, output_name="output_video.mp4")

print(f"\n🎉 [HOÀN TẤT] Video bài giảng đã được tạo thành công: {out_video}")
